### PR TITLE
Add Join function and support for REG_EXPAND_SZ keys

### PR DESCRIPTION
**Pull request by dlon**
A couple of updates used by the winpathfix branch in mullvadvpn-app:
* Read and write to REG_EXPAND_SZ keys with RegistryKey. (Though `::writeValueExpanded()` doesn't seem like the cleanest solution.)
* Added a Join function for strings that lets you choose a delimiter string to use.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/17)

### CODE REVIEW

**Review by mvd-ows — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/17)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[src/libcommon/string.h, line 69 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBJ-0M62QUpF29j9sI:-LqBJ-0M62QUpF29j9sJ:bi8skfj) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/string.h#L69)):*
> ```objc
> 
> std::wstring Lower(const std::wstring &str);
> std::wstring Join(const std::vector<std::wstring>& tokens, const std::wstring &delimiter);
> ```

There is already a `Join` method which uses `,` as delimiter. I would suggest that you update the existing code to be able to specify the delimiter as an argument.
___
*[src/libcommon/string.cpp, line 187 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBJKWw36Oqk2IvhMbH:-LqBJKWw36Oqk2IvhMbI:bu6xv6u) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/string.cpp#L187)):*
> ```cpp
> }
> 
> std::wstring Join(const std::vector<std::wstring> &tokens, const std::wstring &delimiter)
> ```

See previous comment.
___
*[src/libcommon/registry/registrykey.h, line 23 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBJUJ_0Yzw1pZrfaa2:-LqBJUJ_0Yzw1pZrfaa3:brhgg70) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/registry/registrykey.h#L23)):*
> ```objc
> 
> 	void writeValue(const std::wstring &valueName, const std::wstring &valueData);
> 	void writeValueExpanded(const std::wstring &valueName, const std::wstring &valueData);
> ```

I think it might be cleaner to update the existing `writeValue` method that accepts a string, adding an optional parameter that can be used to specify it should be written as `REG_EXPAND_SZ`.

Perhaps:

```
enum class VALUE_STRING_TYPE
{
  REG_SZ,
  REG_EXPAND_SZ,
};

void writeValue(const std::wstring &valueName, const std::wstring &valueData, type = VALUE_STRING_TYPE::REG_SZ);
```

What are your thoughts on this? We would handle REG_MULTI_SZ using a different method, as the need arises.
___
*[src/libcommon/registry/registrykey.cpp, line 302 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBO12D2f2seKdC6E7g:-LqBO12D2f2seKdC6E7h:b-5xnjlc) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/registry/registrykey.cpp#L302)):*
> ```cpp
> 	THROW_UNLESS(ERROR_SUCCESS, status, "Query for registry value data type and data length");
> 
> 	if (actualDataType == REG_EXPAND_SZ)
> ```

Why is this logic necessary? Please always use curly brackets also for one-line bodies.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/17)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mvd-ows)

___
*[src/libcommon/string.h, line 69 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBJ-0M62QUpF29j9sI:-LqBW--RAdPxfSwl5O6m:b-896fix) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/string.h#L69)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

There is already a `Join` method which uses `,` as delimiter. I would suggest that you update the existing code to be able to specify the delimiter as an argument.
</blockquote></details>

Done.
___
*[src/libcommon/registry/registrykey.h, line 23 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBJUJ_0Yzw1pZrfaa2:-LqBWHAL0J1dx5kIuckW:bcn88mg) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/registry/registrykey.h#L23)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I think it might be cleaner to update the existing `writeValue` method that accepts a string, adding an optional parameter that can be used to specify it should be written as `REG_EXPAND_SZ`.

Perhaps:

```
enum class VALUE_STRING_TYPE
{
  REG_SZ,
  REG_EXPAND_SZ,
};

void writeValue(const std::wstring &valueName, const std::wstring &valueData, type = VALUE_STRING_TYPE::REG_SZ);
```

What are your thoughts on this? We would handle REG_MULTI_SZ using a different method, as the need arises.
</blockquote></details>

Agreed. I used `ValueStringType` for consistency with other code:

	enum class ValueStringType
	{
		SZ = REG_SZ,
		EXPAND_SZ = REG_EXPAND_SZ,
	};

	void writeValue(const std::wstring &valueName, const std::wstring &valueData, ValueStringType type = ValueStringType::SZ);
___
*[src/libcommon/registry/registrykey.cpp, line 302 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBO12D2f2seKdC6E7g:-LqBWv6y6nY49lZZNtov:b-qb9fmv) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/registry/registrykey.cpp#L302)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Why is this logic necessary? Please always use curly brackets also for one-line bodies.
</blockquote></details>

`readRaw()` throws if the type doesn't match, so I added it as a workaround. I've updated `readString()` to take a `ValueStringType` argument instead.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/17)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[src/libcommon/registry/registrykey.h, line 23 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBJUJ_0Yzw1pZrfaa2:-LqBY6Dc-s-xru4S6pQL:b-60sbf6) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/registry/registrykey.h#L23)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Agreed. I used `ValueStringType` for consistency with other code:

	enum class ValueStringType
	{
		SZ = REG_SZ,
		EXPAND_SZ = REG_EXPAND_SZ,
	};

	void writeValue(const std::wstring &valueName, const std::wstring &valueData, ValueStringType type = ValueStringType::SZ);
</blockquote></details>

Yes, good point. Consistency is king. Perhaps the individual enumeration values could be named better as well? I checked a few existing enums we have and they all use camelback for the value names. `RegularString`, `ExpandableString`?
___
*[src/libcommon/registry/registrykey.cpp, line 302 at r1](https://reviewable.io/reviews/mullvad/windows-libraries/17#-LqBO12D2f2seKdC6E7g:-LqBZN2d6K5lPWMulDCT:b-qn5lay) ([raw file](https://github.com/mullvad/windows-libraries/blob/d5e971a6dc54ae8c098e14dbc17c38e46ae7913f/src/libcommon/registry/registrykey.cpp#L302)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`readRaw()` throws if the type doesn't match, so I added it as a workaround. I've updated `readString()` to take a `ValueStringType` argument instead.
</blockquote></details>

Perfect.

**Review by mvd-ows — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-libraries/17#-:-LqBbFeID8KjbUZNahCn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
